<!-- Login.svelte -->
<script>
  import { preventDefault } from "svelte/legacy";

  import { onMount } from "svelte";
  import { gun, user, username } from "../../scripts/initGun";
  import SEA from "gun/sea";

  let {
    handleToggleSettings = () => {
      console.log("no handleToggleSettings function implemented");
    },
  } = $props();

  // let username = $state("");
  let pass = $state("");
  let showPassword = $state(false); // State variable to toggle password visibility
  let passwordInputType = $state("password");

  onMount(async () => {
    // username = $username
    // Listen for authentication changes
    gun.on("auth", async () => {
      getUsernameAndPassword();
    });
    getUsernameAndPassword();
  });

  async function getUsernameAndPassword() {
    if (user.is) {
      const encryptedAlias = localStorage.getItem("encryptedAlias");
      const encryptedPass = localStorage.getItem("encryptedPass");
      const pairSerialized = localStorage.getItem("pair");
      console.log(encryptedAlias && encryptedPass && pairSerialized);

      if (encryptedAlias && encryptedPass && pairSerialized) {
        const pair = JSON.parse(pairSerialized); // Deserialize the pair
        const alias = await SEA.decrypt(encryptedAlias, pair);
        username.set(alias)
        pass = await SEA.decrypt(encryptedPass, pair);
      }
    }
  }

  const signUp = () => {
    user.create($username, pass, async (ack) => {
      if (ack.err) {
        console.error("Sign-up error:", ack.err);
      } else {
        console.log("Sign-up successful:", ack);
        signIn();

        // Use the actual key pair generated by GunDB during sign up
        const pair = user._.sea;
        const pairSerialized = JSON.stringify(pair);

        const encryptedAlias = await SEA.encrypt($username, pair);
        const encryptedPass = await SEA.encrypt(pass, pair);

        localStorage.setItem("encryptedAlias", encryptedAlias);
        localStorage.setItem("encryptedPass", encryptedPass);
        localStorage.setItem("pair", pairSerialized);
      }
    });
  };

  const signIn = async () => {
    try {
      console.log($username, pass);
      gun.get(`~@${$username}`).once((data) => {
        console.log("alias lookup:", data);
      });

      const success = await new Promise((resolve, reject) => {
        user.auth($username, pass, async (ack) => {
          if (ack.err) {
            console.error("Sign-in error:", ack.err);
            // Handle sign-in error
            reject(ack.err);
          } else {
            console.log("Sign-in successful:", ack);
            // Proceed with user session initialization
            resolve(true);
          }
        });
      });

      // if (success) {
      //   const pair = user._.sea;
        
      //   const encryptedusername = await SEA.encrypt(username, pair);
      //   const encryptedPass = await SEA.encrypt(pass, pair);
      //   const pairSerialized = JSON.stringify(pair);

      //   localStorage.setItem("encryptedusername", encryptedusername);
      //   localStorage.setItem("encryptedPass", encryptedPass);
      //   localStorage.setItem("pair", pairSerialized);

        // handleToggleSettings();
      // }
    } catch (error) {
      console.error("Error during sign-in:", error);
      // Handle error
    }
  };

  // Function to toggle password visibility
  const togglePasswordVisibility = () => {
    showPassword = !showPassword;
    passwordInputType = showPassword ? "text" : "password";
  };

  // Function to handle input change for password field
  const handlePasswordInput = (event) => {
    pass = event.target.value;
  };

  // Prevent form submission default action
  const handleSubmit = async (event) => {
    event.preventDefault();
    signIn();
  };
</script>

<h1>Login, Register, or Sync</h1>

<div style="padding-bottom: 500px;">
  {#if $username == '' }
    <p>Welcome to MyApps. You can sign-up and login as explained below.</p>
  {:else if user.is}
    <h2>Welcome to Your Profile, {$username}</h2>
  {/if}
  <p>
    Here you can sync your data across devices. If this is your first time, note down your
    automatically generated username and password. You can use these credentials to log in from
    another device to sync your data.
  </p>
  <p>
    If you are syncing your data, then paste below the username and password from your <em
      >initial</em
    > device. Then hit "Sign In".
  </p>
  <p>
    You can also create a new user with your own desired credentials. Simply write your desired
    username and password. Then hit "Sign Up". Now you can sign in with these new credentials across
    other devices too.
  </p>
  <hr />
  <div>
    <form onsubmit={preventDefault(handleSubmit)}>
      <label for="username">Username:</label>
      <input type="text" bind:value={$username} placeholder="Username" />
      <label for="password">Password:</label>
      <input
        type={passwordInputType}
        value={pass}
        oninput={handlePasswordInput}
        placeholder="Password"
      />
      <!-- Eye icon button for toggling password visibility -->
      <button type="button" class="eye-icon" onclick={togglePasswordVisibility}>
        {#if showPassword}
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="red">
            <!-- SVG path for eye icon when password is visible -->
            <!-- Please replace this with the SVG path provided in your example -->
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21"
            />
          </svg>
        {:else}
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <!-- SVG path for eye icon when password is hidden -->
            <!-- Please replace this with the SVG path provided in your example -->
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
            />
          </svg>
        {/if}
      </button>
      <br />
      <button type="submit">Sign In</button>
    </form>
  </div>
  <div>
    <button onclick={signUp}>Sign Up</button>
  </div>
  <!-- {#if message}
      <p>{message}</p>
    {/if} -->
</div>

<style>
  input {
    border: 1px solid gray;
  }

  input:focus {
    outline: none;
  }

  /* Add your CSS here */
  .eye-icon {
    position: relative;
    right: 5px;
    background-color: white;
    border: 1px solid gray;
    margin: 0;
  }

  .eye-icon svg {
    width: 14px;
    height: 14px;
    height: auto;
  }
</style>
